Repository DevOps-Nistagram-Organization/Nistagram-Auth, pull requests merged in 2021-09, with the labels that each got.

#6 Closes #3
  src/main/java/com/nistagram/authentication/controller/AuthenticationController.java
  src/main/java/com/nistagram/authentication/model/dto/LoginRequestDTO.java
  src/main/java/com/nistagram/authentication/model/dto/LoginResponseDTO.java
  src/main/java/com/nistagram/authentication/service/AuthService.java
Labels: backend

#21 Task/auth17
  .dockerignore
  Dockerfile.base
  README.md
Labels: devops

#22 Dockerfile Auth service
  Dockerfile
Labels: devops

#25 Nistagram Auth git-actions
  .github/workflows/ci-pr-develop-pipeline.yml
  .github/workflows/ci-push-develop-pipeline.yml
  .github/workflows/ci-push-main-pipeline.yml
  pom.xml
  publish-dockerhub.sh
Labels: devops

#26 CI main pipeline Nistagram Auth service
  .github/workflows/ci-push-main-pipeline.yml
Labels: devops

#27 New Release Nistagram Auth
  .dockerignore
  .github/workflows/ci-pr-develop-pipeline.yml
  .github/workflows/ci-push-develop-pipeline.yml
  .github/workflows/ci-push-main-pipeline.yml
  .gitignore
  .mvn/wrapper/MavenWrapperDownloader.java
  .mvn/wrapper/maven-wrapper.jar
  .mvn/wrapper/maven-wrapper.properties
  Dockerfile
  Dockerfile.base
  README.md
  mvnw
  mvnw.cmd
  pom.xml
  publish-dockerhub.sh
  src/main/java/com/nistagram/authentication/AuthenticationApplication.java
  src/main/java/com/nistagram/authentication/client/UserClient.java
  src/main/java/com/nistagram/authentication/config/JwtAuthenticationEntryPoint.java
  src/main/java/com/nistagram/authentication/config/JwtRequestFilter.java
  src/main/java/com/nistagram/authentication/config/JwtTokenUtil.java
  src/main/java/com/nistagram/authentication/config/JwtUserDetailsService.java
  src/main/java/com/nistagram/authentication/config/WebSecurityConfig.java
  src/main/java/com/nistagram/authentication/controller/AuthenticationController.java
  src/main/java/com/nistagram/authentication/model/Authority.java
  src/main/java/com/nistagram/authentication/model/User.java
  src/main/java/com/nistagram/authentication/model/dto/AuthRequestDTO.java
  src/main/java/com/nistagram/authentication/model/dto/AuthResponseDTO.java
  src/main/java/com/nistagram/authentication/model/dto/LoginRequestDTO.java
  src/main/java/com/nistagram/authentication/model/dto/LoginResponseDTO.java
  src/main/java/com/nistagram/authentication/model/dto/RegistrationRequestDTO.java
  src/main/java/com/nistagram/authentication/model/dto/RegistrationResponseDTO.java
  src/main/java/com/nistagram/authentication/model/dto/UserInfoDTO.java
  src/main/java/com/nistagram/authentication/model/dto/UserInfoRegistrationDTO.java
  src/main/java/com/nistagram/authentication/repository/AuthorityRepository.java
  src/main/java/com/nistagram/authentication/repository/UserRepository.java
  src/main/java/com/nistagram/authentication/service/AuthService.java
  src/main/resources/application.yml
  src/main/resources/dataDev.sql
  src/test/java/com/nistagram/authentication/AuthenticationApplicationTests.java
Labels: backend, devops, frontend
